# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.define "m-k8s" do |cfg|
    
    cfg.vm.box = "bento/ubuntu-24.04"
    cfg.vm.box_check_update = false

    cfg.vm.provider "vmware_desktop" do |vm|
      vm.gui = false
      vm.vmx["memsize"] = "2048"
      vm.vmx["numvcpus"] = "2"
    end
    cfg.vm.host_name = "m-k8s"
    cfg.vm.network "public_network", ip: "192.168.219.17"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"

  "ssh"
    cfg.vm.synced_folder "../data", "vagrant", disabled: true
    cfg.vm.provision "shell", path: "install_pkg.sh"
  end
end
